name: Deploy Supabase Functions

on:
  push:
    branches:
      - main # Deploy only when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Go back one step
        run: cd ..

      - name: Deploy Edge Function
        run: |
          for dir in supabase/functions/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              echo "Deploying function: $name"
              supabase functions deploy "$name" --project-ref $PROJECT_REF
            fi
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
